repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - types-click
          - types-toml
        exclude: ^tests/

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.12
    hooks:
      - id: uv-lock